<SPAN class="p4hdr2">Basic Blackjack</SPAN><SPAN class="p1"><BR><BR>There are many basic strategies for blackjack, depending 
							on the casino's rules and the number of decks used. The basic 
							strategy outlined here is based on the four-deck game as 
							played in Las Vegas. The object of the game is to beat the 
							dealer with a total equal to or less than 21, without going 
							over 21 or bust.<BR><BR><B>Rules of the Game</B><BR><BR>Before any cards are dealt, the player must wager. He does 
							this by placing his bet in the designated space in front 
							of his table position. The dealer then deals two cards to 
							each of the players, and two to himself (one of the dealer's 
							cards is dealt face up and one is dealt facing down). Face 
							cards (kings, queens and jacks) count as 10, ace counts as 
							one or 11 (as the player chooses) and all other cards are 
							counted at their face value.<BR><BR><I>BLACKJACK</I><BR>If the player's first two cards are an ace and a 10 or face 
							card, he wins. However, if the dealer also has a blackjack, 
							it is a standoff, as are all ties or pushes. A winning blackjack 
							pays the player 3 to 2.<BR><BR><I>HIT or STAND</I><BR>Hit means to draw another card (which the player signifies 
							by scraping the table with his cards or a similar hand motion). 
							Stand means no more cards (which the player signals by placing 
							his cards under his wager or moving his hand in a horizontal 
							direction. If the player hits and busts (goes over 21), he 
							immediately turns his cards over and his wager is lost.<BR><BR><I>DOUBLE DOWN</I><BR>The player is allowed to double the bet on his first two 
							cards and draw one additional card only to improve his hand.<BR><BR><I>SPLITTING PAIRS</I><BR>If the first two cards a player is dealt are a pair, he may 
							split them into two separate hands, bet the same amount on 
							each and then play them separately. Aces receive only one 
							additional card. After splitting, A-10 counts as 21 and not 
							as blackjack.<BR><BR><I>INSURANCE</I><BR>If the dealer's up card is an ace, the player may take insurance, 
							a bet not exceeding one-half his original bet. If the dealer's 
							down card is a 10 or any face card, the player wins 2 to 
							1. Any other card means a win for the dealer.<BR><BR>The dealer must draw on 16 and stand on 17. In some casinos, 
							the dealer is required to draw on soft 17.<BR><BR></SPAN>