<p><b><font face="Arial, Helvetica, sans-serif" size="3">Main Login</font></b></p>
<p><b><font face="Arial, Helvetica, sans-serif" size="2">Player Name </font></b><font face="Arial, Helvetica, sans-serif" size="2">- 
  The player name you are using in the game.</font></p>
<p><b><font face="Arial, Helvetica, sans-serif" size="2">Password </font></b><font face="Arial, Helvetica, sans-serif" size="2">- 
  The password you are using for the above player name.</font></p>
<p><b><font face="Arial, Helvetica, sans-serif" size="2">Language</font></b><font face="Arial, Helvetica, sans-serif" size="2"> 
  - Select the language you would like to play the game in. The game will try 
  to use the selected language in all displays and communications.</font></p>
<p><b><font face="Arial, Helvetica, sans-serif" size="2">New Player</font></b><font face="Arial, Helvetica, sans-serif" size="2"> 
  - Click this button to create a new player.</font></p>
<p><b><font face="Arial, Helvetica, sans-serif" size="2">Login</font></b><font face="Arial, Helvetica, sans-serif" size="2"> 
  - After you have entered your player name and password click this button to 
  log into the game.</font></p>
<p><b><font face="Arial, Helvetica, sans-serif" size="2">Forums</font></b><font face="Arial, Helvetica, sans-serif" size="2"> 
  - If a forum has been set for the game this button will take you to the external 
  forums.</font></p>
<p><b><font face="Arial, Helvetica, sans-serif" size="2">Rankings</font></b><font face="Arial, Helvetica, sans-serif" size="2"> 
  - Clicking this button will display the player ranking list showing all players 
  currently in the game and their player rankings.</font></p>
<p><b><font face="Arial, Helvetica, sans-serif" size="2">Settings</font></b><font face="Arial, Helvetica, sans-serif" size="2"> 
  - Clicking this button will display some of the default settings the admin has 
  set for the game (turns, colonist linits, ect).</font></p>
<p><b><font face="Arial, Helvetica, sans-serif" size="2">FAQ</font></b><font face="Arial, Helvetica, sans-serif" size="2"> 
  - This will display a brief instruction about different things in the game.</font></p>
<p><b><font face="Arial, Helvetica, sans-serif" size="2">Web Site</font></b><font face="Arial, Helvetica, sans-serif" size="2"> 
  - If the admin has designated a web site for the game this button will appear. 
  Clicking the button will take you to the site.</font></p>
<p><b><font face="Arial, Helvetica, sans-serif" size="2">Servers</font></b><font face="Arial, Helvetica, sans-serif" size="2"> 
  - This buttopn will take you to AATrades Master Server List. This list shows 
  all of the availible public games people can play.</font></p>
<p><font face="Arial, Helvetica, sans-serif" size="2"><b>Local Nova News</b> - 
  This button will display the public news about what has been happening in the 
  game.</font></p>
<p> <b><font face="Arial, Helvetica, sans-serif" size="2">AATRADE / NGS / BNT 
  Developers</font></b><font face="Arial, Helvetica, sans-serif" size="2"> - Clicking 
  this link will display information about the developers of AATraders, NGS and 
  BNT. Links are included to the developer web sites, forums and email.</font></p>
<p><font face="Arial, Helvetica, sans-serif" size="2"><b>Springfield Net</b> - 
  One of AATrade Developers Web Sites.</font><br>
  <br>
  <b><font face="Arial, Helvetica, sans-serif" size="2">Alien Assault Traders</font></b><font face="Arial, Helvetica, sans-serif" size="2"> 
  - Direct link to the Sourceforge Developer Project for AATraders.</font></p>
<p>&nbsp;</p>
