
                       <br>
						When you first login you will be taken to the options screen. This screen allows you to customize several different things about the game.   <p>
<b>Password</b>- This is where you can change the random password the system sent you to something you can more easily remember.
</p>            
<p>
<b>Language</b> - This is your default language.  We currently provide support for many different languages although they are still not complete we are slowly getting the translations from our players for the many different languages.
</p> 
<p>
<b>Templates</b> - This allows you to change the page layout for your game.  Our recommended layouts are the Alien Assault Traders Paged Commands or the Alien Assault Traders Drop Down Menu templates.  These templates have all the extra features added to make navigating the new game version much easier.  However you are more than welcome to use any template in the system.  Most of all the game is now templated so everyone is welcome to come up with their own template designs and depending on the game owner they may have several different template styles available.  Be sure to test both templates to see if they fit your style of play.  Both the default templates support a variety of hot keys where the other templates do not.
</p>
<p>
<b>Avatars</b> - Each player can select from a directory of images what they want their character to look like or if the server supports it they can upload their own.  Avatars are 64 pixel width X 64 pixel height graphics, either gif's or jpg's.  Please keep your uploaded avatars clean so game admins don't have to do as much censorship work.
</p>
<p> <b>Team Icons</b> - Once you set up a team you can select an icon for your 
  team. This can only be done by the team coordinator. Much like avatars you can 
  also upload your own and they must be 64 pixel width X 64 pixel height graphics, 
  either gif's or jpg's. </p>
<p><b>Local and Galaxy Map Width</b> - This controls how many sectors should be 
  displayed per line of the local and galaxy map display. The default setting 
  is 50 sectors and should fit on most displays. If you have a smaller or larger 
  browser window adjust the number per line to fit.</p>
<p>
<b>Profiles</b> - Help track your scores for all the games you are playing in.  You can login to the profiles server at <a href="http://profiles.aatraders.com">http://profiles.aatraders.com</a> and create a profile.  Once your profile is created you can build your mini profiles site with information about your character.  Communicate with other players, write your own blog or comment on other players.  You tie your profile to a game by clicking the click here area at the bottom of the options page.  It will ask you for your profile password.  Once you submit it, you should have a link in the rankings tied directly to your profile site.   If this did not work you may have to delete your profile out of the game and try again.  
</p>
<p>
<i>
Note: Game stats for profiles are only updated if you log out of the game.  If you never log out your stats will not be updated.</i>
</p>                    