<?php
// This program is free software; you can redistribute it and/or modify it   
// under the terms of the GNU General Public License as published by the     
// Free Software Foundation; either version 2 of the License, or (at your    
// option) any later version.                                                
// 
// File: skin_config.inc

$color_header = "#000000"; // Used for headers in certain files.
$color_line1 = "#000000"; // Used for two-line alternating tables
$color_line2 = "#000000"; // Used for two-line alternating tables
$general_text_color = "#ff0000"; // Used for text throughout
$general_highlight_color = "ff0000"; // Used for highlighted text throughout
$main_table_color = "#000000"; // Used for tables on main
$main_table_heading = "#ff0000"; // Used for table headings for tables on main
$header_bg_color = "#000000";
$header_text_color = "#ff0000";
$header_link_color = "#ff0000";
$header_alink_color = "#00ff00";
$header_vlink_color = "#00ff00";

// Yes indeed, every image in the game is configurable!
$background_image = "templates/" . $templatename . "images/bgoutspace1.png"; // Used for the background throughout
$log_background_image = "templates/" . $templatename . "images/top_panel.png";
$igb_background_image = "not implemented yet";
$bnn_head_image = "templates/" . $templatename . "images/fnnhead.gif";

$planettypes[0] = "templates/" . $templatename . "images/planet1.gif";
$planettypes[1] = "templates/" . $templatename . "images/planet2.gif";
$planettypes[2] = "templates/" . $templatename . "images/planet3.gif";
$planettypes[3] = "templates/" . $templatename . "images/planet4.gif";
$planettypes[4] = "templates/" . $templatename . "images/planet5.gif";
$planettypes[5] = "templates/" . $templatename . "images/planet6.gif";
$planettypes[6] = "templates/" . $templatename . "images/planet7.gif";
$planettypes[7] = "templates/" . $templatename . "images/planet8.gif";
$planettypes[8] = "templates/" . $templatename . "images/planet9.gif";
$planettypes[9] = "templates/" . $templatename . "images/planet10.gif";
$planettypes[10] = "templates/" . $templatename . "images/planet11.gif";


$startypes[0] = "templates/" . $templatename . "images/spacer.gif";
$startypes[1] = "templates/" . $templatename . "images/redstar.png";
$startypes[2] = "templates/" . $templatename . "images/orangestar.png";
$startypes[3] = "templates/" . $templatename . "images/yellowstar.png";
$startypes[4] = "templates/" . $templatename . "images/greenstar.png";
$startypes[5] = "templates/" . $templatename . "images/bluestar.png";

$probetype = "templates/" . $templatename . "images/probe.gif";
$fightertype = "templates/" . $templatename . "images/fighters.gif";
$minetype = "templates/" . $templatename . "images/mines.gif";
$debris = "templates/" . $templatename . "images/debris.gif";

$tile['upgrades'] ="templates/" . $templatename . "images/armour.png";
$tile['devices']  ="templates/" . $templatename . "images/devices.png";
$tile['spacedock']  ="templates/" . $templatename . "images/spacedock.png";
$tile['casino']  ="templates/" . $templatename . "images/casino.gif";
$tile['ore']	  ="templates/" . $templatename . "images/ore.png";
$tile['organics'] ="templates/" . $templatename . "images/organics.png";
$tile['energy']   ="templates/" . $templatename . "images/energy.png";
$tile['goods']	="templates/" . $templatename . "images/goods.png";
$tile['none']	 ="templates/" . $templatename . "images/space.png";
$tile['unknown']  ="templates/" . $templatename . "images/uspace.png";

$porttype['upgrades'] ="templates/" . $templatename . "images/port_upgrades.gif";
$porttype['devices']  ="templates/" . $templatename . "images/port_devices.gif";
$porttype['shipyard']  ="templates/" . $templatename . "images/port_shipyard.gif";
$porttype['spacedock']  ="templates/" . $templatename . "images/port_spacedock.gif";
$porttype['casino']  ="templates/" . $templatename . "images/port_casino.gif";
$porttype['ore']	  ="templates/" . $templatename . "images/port_ore.gif";
$porttype['organics'] ="templates/" . $templatename . "images/port_organics.gif";
$porttype['energy']   ="templates/" . $templatename . "images/port_energy.gif";
$porttype['goods']	="templates/" . $templatename . "images/port_goods.gif";
$porttype['none']	 ="templates/" . $templatename . "images/spacer.gif";
?>
