<?php
$l_debris_title             = "Debris Field";
$l_debris_addturns             = "A Search Of The Debris Field Reveals An Alien Device. As You Load It Into The Cargo Bay, It Starts To Glow....Then It Goes Inert...You Find That [amount] Turns Have Been Added.";
$l_debris_removeturns             = "A Search Of The Debris Field Reveals An Alien Device. As You Load It Into The Cargo Bay, It Starts To Glow....Then It Goes Inert...You Find That [amount] Turns Have Been Lost.";
$l_debris_addtorps             = "A Search Of The Debris Field Allows You To Collect The [amount] Torpedos Scattered Within.";
$l_debris_removetorps             = "A Search Of The Debris Field Allows You To Collect The Torpedos Scattered Within. As The Last One Is Put Into Storage It Explodes And Destroys [amount] Torpedos.";
$l_debris_addfighters             = "A Search Of The Debris Field Allows You To Collect The [amount] Fighters Scattered Within.";
$l_debris_removefighters             = "A Search Of The Debris Field Allows You To Collect The Fighters Scattered Within. As The Last One Is Put Into Storage It Explodes And Destroys [amount] Fighters.";
$l_debris_addarmor             = "A Search Of The Debris Field Reveals A Derelict Ship With Removable Armor You Can Add To Your Ship.[amount] Units Of Armor Added";
$l_debris_removearmor             = "A Search Of The Debris Field Reveals Nothing. As You Leave, You Discover A Nano-Virus Is Eating Your Armor. In Your Hurry To Remove It, You Are Forced To Destroy Some Of Your Armor. [amount] Units Of Armor Lost";
$l_debris_addenergy             = "A Search Of The Debris Field Reveals Energy Storage Modules.[amount] Units Of Energy Added.";
$l_debris_removeenergy             = "A Search Of The Debris Field Reveals Energy Storage Modules. As You Hook-Up The Last Module, It Overloads Your Energy Systems.[amount] Units Of Energy Removed";
$l_debris_addcredits             = "A Search Of The Debris Field Reveals An Alien Device Worth [amount] Credits!.";
$l_debris_removecredits             = "A Search Of The Debris Field Reveals An Alien Device. As You Load It Into The Cargo Bay, It Starts To Glow. Suddenly Your Ship Goes Dark....When Power Is Restored You Find That You Were Boarded By Raiders. They Made Off With [amount] Credits Worth Of Cargo.";
$l_debris_nothing             = "A Search Of The Debris Field Reveals Nothing.";
$l_debris_wormhole             = "A Search Of The Debris Field Reveals An Alien Device. As You Load It Into The Cargo Bay, It Starts To Glow. Suddenly Your Ship Goes Dark....When Power Is Restored You Find That You Are In Sector [sector].";
$l_debris_upgradelevel             = "A Search Of The Debris Field Reveals Nothing. As You Leave, You Discover A Nano-Virus That Upgrades Your [tech] By [levels] Levels.";
$l_debris_degradelevel             = "A Search Of The Debris Field Reveals Nothing. As You Leave, You Discover A Nano-Virus That Downgrades Your [tech] By [levels] Levels Before You Can Stop It.";
$l_debris_upgradeall             = "A Search Of The Debris Field Reveals Nothing. As You Leave, You Discover A Nano-Virus That Upgrades All Of Your Tech Levels By [level].";
$l_debris_degradeall             = "A Search Of The Debris Field Reveals Nothing. As You Leave, You Discover A Nano-Virus That Downgrades All Of Your Tech Levels By [level] Before You Can Stop It.";
$l_debris_addsg             = "A Search Of The Debris Field Reveals A Usable Sector Genesis Device.";
$l_debris_removesg             = "A Search Of The Debris Field Reveals Nothing. As You Leave, You Discover A Nano-Virus That Destroys One Of Your Sector Genesis Devices.";
$l_debris_addnova             = "A Search Of The Debris Field Reveals A Usable Nova Bomb.";
$l_debris_removenova             = "A Search Of The Debris Field Reveals An Alien Device. As You Load It Into The Cargo Bay, It Starts To Glow. Suddenly Your Ship Goes Dark....When Power Is Restored You Find That Your Nova Bomb Has Become Inert.";
$l_debris_destroyship             = "A Search Of The Debris Field Reveals An Alien Device. As You Load It Into The Cargo Bay, It Starts To Glow. Suddenly It Explodes Destroying Your Ship.  Fortunately You Have An Escape Pod.";
$l_debris_zeroship             = "A Search Of The Debris Field Reveals An Alien Device. As You Load It Into The Cargo Bay, It Starts To Glow. Suddenly Your Ship Goes Dark....When Power Is Restored You Find That Your Ships Has Suffered Massive Damage.All Of Your Ships Tech Levels Are Reduced To 0, But Your Ship Survives.";
$l_debris_cantfind             = "Cannot Locate The Debris Field.";

?>
