<?php
$l_news_title            = "Universe News";
$l_news_Info             = "MNN Is The Galaxy's Leader<br>In News And Information Delivery.<br>Staffed 24 Hours, Seven Days A Week By Our <br>Dedicated Staff In MNN's Headquarters <br>In Mornoc Prime And Our Bureaus Galaxy Wide!";
$l_news_For              = "News For";
$l_news_prev             = "Previous Day";
$l_news_next             = "Next Day";
$l_news_none             = "Sorry, NothIng New To Report.";
$l_news_flash            = "News Flash";
$l_news_end              = "Please Stay Tuned For Updates";

// New News Items

$l_news_Planets		 = " Planets";
$l_news_cols		 = " Million Colonists";
$l_news_p_headlIne 	 = "[player]'s Empire Now Has ";

$l_created_universe             = 'Universe Creation';
$l_created_universe_full        = 'Scientists Galaxy Wide All Agree That Today Is The Universes 1st Day Of Existence';

$l_killheadlIne		 =" Was Killed In An Accident";

$l_news_killed 		 = "[name] Was Killed Today. Captain [name] Forgot To Buy A Pod, And Now Has Gone To Meet The Gods.....";

$l_news_p_text5		 = "The Rising Empire Of [name] Now Has Five Planets, MNN Will Watch The Actions Of [name] More Closely In The Future!";

$l_news_p_text10	 = "The Growing Empire Of [name] Now Controls Ten Planets, MNN Reporters  Say That Further Expansion Of [name]'s Empire Might Lead To War!";

$l_news_p_text25	 = "The Huge Empire Of [name] Has Now Colonized 25 Planets, In An Interview, [name] Announced That They Will Not Be Slowing Thier Expansion Any Time In The Near Future!";

$l_news_p_text50	 = "The Enormous Empire Of [name], Has Now Colonized 50 Planets. MNN Reporters Found Out That The Empire Of [name] Has Been Quietly Upgrading Planets. In An Interview, [name] Announced That The Upgrades Are For Defence Only!";

$l_news_c_text25	 = "The Rising Empire Of [name] Now Has 25 Million Colonists, MNN Will Watch The Actions Of [name] More Closely In The Future, But Its Highly Likely That Birthrates Are Going To Explode!";

$l_news_c_text100	 = "The Aspiring Empire Of [name] Now Has 100 Million Colonists, After An Explosion Of Birth Rates, [name] Colonies Seemed To Be A Good Place For Families To Settle!";

$l_news_c_text500	 = "The Growing Empire Of [name] Now Has 500 Million Colonists, [name] Said In An Interview, 'Colonization Of The Galaxy Has Just Begun'";

$l_news_c_text1000	 = "The Humongous Empire Of [name] Now Has One Billion Colonists, MNN Reporters Found Out That [name] Is In Possesion Of Some Weird Cloning Device, Allowing Him To Breed New Colonists In Large Quantities. The Economic Strength Of This Empire Is Enormous. MNN Fears That [name] Is Preparing For War";

$l_news_indi_short	 = "MNN Rumor: Over [Planets] Declare Independance.";

$l_news_indi	 = "MNN Has It On Good Authority That Over [Planets] Planets Have Become Independant. Reports Indicate That Poor Management By Planatary Rulers Is To Blame";

$l_news_nova_short	 = "MNN Report: [name] Has Used A Nova Bomb.";

$l_news_nova	 = "MNN Has Breaking News That [name] Has Used The Feared Nova Bomb [total] Time(s) To Destroy A Planet And All Ships On It.";

$l_news_nova_m_short	 = "MNN Report: [name] Used A Nova Bomb And Missed.";

$l_news_nova_m	 = "MNN Has Breaking News That [name] Has Used The Feared Nova Bomb [total] Time(s) To Try And Destroy A Planet.  The Nova Bomb Blew Up Outside The Planets Atmosphere And Caused Massive Damage To The Planetary Infrastructure.";

$l_news_bounty	 = "MNN Report: [name] Placed A [amount] Credit Bounty On [name2].";

$l_news_attackerpod_p_short	 = "MNN Report: [name]'s Ship Was Destroyed.";

$l_news_attackerpod_P	 = "[name]'s Ship Was Destroyed By Planatary Defences While Attacking A Planet.  Fortunately [name] Had An Escape Pod And Survived.";

$l_news_attackerdie_p_short	 = "MNN Report: [name] Dies!";

$l_news_attackerdie_p	 = "[name]'s Ship Was Destroyed By Planatary Defences While Attacking A Planet, [name] Paid The Ultimate Price For Failing To Buy An Escape Pod.";

$l_news_destroyed_p_short	 = "MNN Report: [name] Attacked A Planet And Caused Its Destruction!";

$l_news_destroyed_p	 = "[name] Attacked [total] Planet(s) Owned By [owner]. The Population Of Each Planet, Rather Then Being Ruled By A Pirate, Choose Planatary Destruction!";

$l_news_defeated_p_short	 = "MNN Report: [name] Attacked And Defeated A Planet!";

$l_news_defeated_p	 = "[name] Attacked [total] Planet(s) Owned By [owner] And Defeated The Planetary Defense Forces!";

$l_news_notdefeated_p_short	 = "MNN Report: [name] Attacked A Planet And Lost!";

$l_news_notdefeated_p	 = "[name] Attacked [total] Planet(s) Owned By [owner] And The Planetary Defenses Held AgaInst The Attacks!";

$l_news_targetepod_short	 = "MNN Report: [name] Attacked [owner] And Won!";

$l_news_targetepod	 = "[name] Attacked [owner]'s Ship And Destroyed It Completely.  Fortunately [owner] Had An Escape Pod And Survived.";

$l_news_targetdies_short	 = "MNN Report: [name] Attacked [owner] And killed Them!";

$l_news_targetdies	 = "[name] Attacked [owner]'s Ship And Destroyed It Completely.[owner] Paid The Ultimate Price For Failing To Buy An Escape Pod.";

$l_news_fedcolbounty_short	 = "MNN Report: Mornoc Alliance Cracks Down On [name]!";

$l_news_fedcolbounty	 = "The Mornoc Battle Cruiser 'Targh' Exacted Retribution On The Space Pirate [name] Today!  [name], Who Violated Several Space Treaties, Was Engaged By The Battle Cruiser 'Targh', Which Inflicted [amount] Credits Worth Of Damage On [name]'s Vessel.  Mornoc Alliance Officials Promise Further Such Actions In The Future!";

?>
