<?php
$l_shout_title            = "Shout Box";
$l_shout_title2              = ".:: SHOUTBOX ::.";
$l_shout_public         = "Public";
$l_shout_team             = "Band";
$l_shout_smiles            = "Smilie's";
$l_shout_else          = "else";
$l_shout_refresh          = "Refresh";
$l_shout_close          = "Close Window";
$l_shout_saved          = "Shout saved!";
$l_shout_return          = "Return to the ";
?>