<?php

// Confirmed common to multiple files:

$l_zname[1] 		 = "Unchartered Space";
$l_zname[2] 		 = "Mornoc Alliance Space";
$l_zname[3] 		 = "Alliance Space";
$l_zname[4] 		 = "War Zone";

$l_nova 		 = "Nova";
$l_nova 		 = "Nova Bomb";
$l_lssd 		 = "Last ship seen device";
$l_lss 			 = "Last ship seen in this sector";
$l_log_text[LOG_TOW] 	 = "Your ship has been towed from sector [sector] to sector [newsector] because your average tech level exceeded the limit value of [hull] or you have a ship in storage.";

// Common to : warpedit 1-3.php

$l_warp_title		 = "Use Warp Editor";
$l_warp_turn		 = "You need at least one turn to use a warp editor.";
$l_warp_none		 = "You do not have any warp editors.";
$l_warp_forbid		 = "Using a Warp Editor in this sector is not permitted.";
$l_swarp_forbid		 = "Using a Warp Editor to or from SG sectors is not permitted.";
$l_warp_nosector	 = "Sector does not exist.";

// Not yet confirmed common to multiple files:

$l_yes 			 = "Yes";
$l_no			 = "No";
$l_here			 = "here";
$l_submit		 = "Submit";
$l_reset		 = "Reset";
$l_all			 = "All";
$l_max			 = "Max";

$l_ore			 = "Ore";
$l_commodities		 = "Commodities";
$l_organics		 = "Organics";
$l_goods		 = "Goods";
$l_energy		 = "Energy";
$l_colonists		 = "Colonists";
$l_credits 		 = "Credits";
$l_units		 = "units of ";
$l_special		 = "Special";
$l_upgrade_ports	 = "Upgrades";
$l_device_ports		 = "Devices";
$l_spacedock		 = "Spacedock";
$l_casino		 = "Casino";

$l_cargo		 = "Cargo";
$l_fighters		 = "Fighters";
$l_mines		 = "Mines";
$l_torps		 = "Torpedoes";

$l_none			 = "None";
$l_unnamed		 = "Unnamed";
$l_name			 = "Name";
$l_unowned		 = "Unowned";
$l_unknown		 = "Unknown";
$l_clickme 		 = "Click here";
$l_player  		 = "Player";
$l_ship			 = "Ship";
$l_ships		 = "Ships";
$l_set			 = "set";
$l_realspace		 = "Realspace";
$l_armourpts		 = "Armor points";
$l_links		 = "Links";
$l_login_email          = "E-mail Address:";
$l_add			 = "Add";
$l_teamforum			 = "Team Forum";
$l_teamships			 = "Team Ships";
$l_tutorial			 = "Tutorial/Help";
$l_avatar			 = "Avatar";
$l_teamicon			 = "Team Icon";
$l_debris			 = "Debris";
$l_localmap			 = "Local Map";
$l_arm_weap              = "Armor & Weapons";
$l_3dmap			 = "3D Galaxy Map";

$l_spacebeacon = "Space Beacon";
$l_spaceprobes = "Space Probes";
$l_warpeditors = "Warp Editors";
$l_genesistorps = "Genesis Torpedoes";
$l_sgtorps = "SG Torpedos";
$l_minesfighters = "Mines/Fighters";
$l_ewarp = "Emergency Warp";
$l_reports = "Reports";
$l_shipinfo = "Ship Info";
$l_sectornotes = "Sector Notes";
$l_maps = "Maps";
$l_messages = "Messages";
$l_shiptype = "Ship Type";
$l_help = "Help";
$l_rank = "Rank";

$l_teamplanets = "Team Planets";
$l_teamdefences = "Team Defences";
$l_planetstatus = "Planet Status";
$l_planetdefences = "Planet Defences";
$l_changeproduction = "Change Production";
$l_galacticarm = "Galactic Arm";

$l_armor		 = "Armor";
?>
