<?php
$l_opt_title             = "Options";
$l_opt_chpass            = "Change password";
$l_opt_curpass           = "Current password:";
$l_opt_newpass           = "New password:";
$l_opt_newpagain         = "New password (again):";
$l_opt_userint           = "User interface";
$l_opt_usenew            = "Use new layout?";
$l_opt_lang              = "Language";
$l_opt_template              = "Template";
$l_opt_select            = "Select One:";
$l_opt_enabled           = "Enabled";
$l_opt_save              = "Save";
$l_opt_teamicon              = "Team Icon";
$l_opt_shipname              = "Shipname:";
$l_opt_mapwidth              = "Local and Galaxy Map Width:";
$l_opt_profiletitle = "Profile";
$l_opt_profile = "If you have a Player Profile at <a href='http://profiles.aatraders.com'>profiles.aatraders.com</a> and would like to register this game with that profile click ";
$l_opt_profilereg = "Registered with Profile Server";
$l_opt_profilerereg = "Re-register Player Profile for this game at <a href='http://profiles.aatraders.com'>profiles.aatraders.com</a> click ";
?>
