<?php
$l_beacon_title          = "Deploy Space Beacon";
$l_beacon_notpermitted   = "Deploying Space Beacons In This Sector Is Not Permitted.";
$l_beacon_reads          = "Present Beacon Reads";
$l_beacon_none           = "There Presently Isn't A Beacon In This Sector.";
$l_beacon_enter          = "Enter Text For Beacon";
$l_beacon_nowreads       = "Beacon Now Reads";
$l_beacon_donthave       = "You Do Not Have A Space Beacon.";
?>
