<?php
$l_by_title              = "Bounties";
$l_by_noturn             = "You Need At Least One Turn To Place Or Modify A Bounty.";
$l_by_amount             = "Bounty Amount";
$l_by_place              = "Place Bounty";
$l_by_nobounties         = "There Are Currently No Bounties.";
$l_by_bountyon           = "Bounty On";
$l_by_placedby           = "Placed By";
$l_by_thefeds            = "The Mornoc Alliance";
$l_by_cancel             = "Cancel";
$l_by_yourself           = "You Can Not Place A Bounty On Your Self.";
$l_by_notenough          = "You Do Not Have Enough credits To Place A Bounty Of That Amount.";
$l_by_toomuch            = "You Can Not Place That Bounty. Maximum Bounty Allowed On Another Player Is [percent] Percent Of Your Net Worth";
$l_by_zeroamount         = "Bounties Must Be Greater Than 0 Credits.";
$l_by_placed             = "The Bounty Has Been Placed.";
$l_by_nobounty           = "That Bounty No Longer Exists.";
$l_by_notyours           = "That Bounty Was Not Placed By You.";
$l_by_canceled           = "The Bounty Has Been Canceled.";
$l_by_action             = "Action";
$l_by_placebounty        = "Place Or View Bounties.";
$l_by_moredetails        = "Click On The Name For More Details.";
$l_by_fedbounty          = "<font color='red' size='4'><b>Attacking This Player Would Result In The Mornoc Alliance Placing A Bounty On You.</b></font>";
$l_by_fedbounty2         = "<font color='red' size='4'><b>The Mornoc Alliance Does Not Approve Of Attacking Much Smaller Players. It Has Placed A Bounty On You.</b></font>";
$l_by_notexists          = "The Player You Are Putting The Bounty On Does Not Exist.";
$l_by_destroyed          = "You Can Not Place A Bounty On A Player With A Destroyed Ship.";
$l_by_nofedbounty		 = "You Will Not Receive A Bounty If You Attack This Players Ship Or Planet.";
$l_by_fedcollectonly		 = "Only The Mornoc Alliance Can Collect Bounty";
$l_gotobounty          ="Click <A HREF=bounty.php>here</A> To Return To The Bounty Menu.";

$l_by_fedbountyspy          = "<font color='red' size='4'><b>Placing A Spy On This Players Planet Would Result In The Mornoc Alliance Placing A Bounty On You.</b></font>";
$l_by_fedbountyspy2         = "<font color='red' size='4'><b>Mornoc Alliance Does Not Approve Of Placing Spies On Much Smaller Players Planets. It Has Placed A Bounty On You.</b></font>";
$l_by_nofedbountyspy		 = "You Will Not Receive A Bounty If You Place A Spy On This Players Planet.";
$l_pay_partial = "Make Partial Payment";
$l_pay_button = "Pay";

?>
