<?php
$l_sn_title          = "Sector Notes for sector";
$l_sn_pntitle          = "Sectors with Personal Notes";
$l_sn_tntitle          = "Sectors with Band Notes";
$l_sn_psntitle          = "Personal Sector Notes";
$l_sn_tsntitle          = "Band Sector Notes";
$l_sn_editnote          = "Edit Sector Note:";
$l_sn_deleteedit          = "Delete or Edit:";
$l_sn_addnote          = "Add Sector Note:";
$l_sn_listps          = "List Sectors with Personal Notes";
$l_sn_listts          = "List Sectors with Band Notes";
$l_sn_addteam          = "Add Band";
$l_sn_deleteteam          = "Delete Band";
$l_sn_saveteam          = "Save Band";
$l_sn_deletepersonal          = "Delete Personal";
$l_sn_addpersonal          = "Add Personal";
$l_sn_savepersonal          = "Save Personal";
$l_sn_editpersonal          = "Edit Personal";
$l_sn_editteam          = "Edit Band";

?>
