<?php
$l_autoroute_missingwarp          = "Next Warplink Is Missing In This Sector.  Warp Move Aborted.<br>";
$l_autoroute_fighterabort   = " - Move Aborted Due To Fighters In The Sector.<br>";
$l_autoroute_turns          = " - Deducted [triptime] Turns And Moved To [targetlink]<br>";
$l_autoroute_noturns           = " - You Are Out Of Turns, Please Wait For The Scheduler To Run.<br>";
$l_autoroute_title          = "Auto Routes";
$l_autoroute_id       = "Auto Route ID";
$l_autoroute_start       = "Auto Route Start";
$l_autoroute_destination       = "Auto Route Destination";
$l_autoroute_warps       = "Auto Route Warps";
$l_autoroute_deleteroute       = "Delete Route";
$l_autoroute_info       = "Click On The Start Sector To Realspace To That Sector And Start Warping To The destination Sector.";
$l_autoroute_delete2       = "Delete Routes";
$l_autoroute_noroutes       = "No Auto Routes";
$l_autoroute_createroute       = "Create New Auto Route";
$l_autoroute_deleted       = "Auto Routes Deleted.";
$l_autoroute_return       = "Return To Auto Route Menu Click";
$l_autoroute_created       = "Auto Route Has Been Created.";
$l_autoroute_realmove       = "Realspace Move To Sector";
$l_autoroute_warpmove       = "Warp Move To Next Sector";
$l_autoroute_warpfinal       = "Warp Move to Final Sector";
?>
