<?php
$l_news_planets		 = " planets";
$l_news_cols		 = " Million colonists";
$l_news_p_headline 	 = "[player]'s Empire now has ";

$l_killheadline		 =" was killed in an accident";
$l_news_killed 		 = "[name] was killed in a tragic accident today. How heroic - captain [name] was the last member on board of his ship, when he noticed there was no escape pod left for him. May he rest in peace!";
$l_news_p_text5		 = "The rising empire of [name] now has five planets, the MNN will watch the actions of [name] more closely in the future!";
$l_news_p_text10	 = "The growing empire of [name] now controls ten planets, Reports of MNN say that further expansion of [name] might lead to war!";
$l_news_p_text25	 = "The huge empire of [name] colonized 25 planets already, in an interview, [name] announced that he might consider slowing down his expansion in the future!";
$l_news_p_text50	 = "The enormous vast empire of [name], represented by 50 planets in the whole galaxy is getting a threatening strength. One of the MNN reporters found out that [name] is upgrading his ship planning a major war. In an interview [name] announced that is done on defence purpose only!";
$l_news_c_text25	 = "The rising empire of [name] now has 25 million colonists, the MNN will watch the actions of [name] more closely in the future, but its highly obvious that birthrates are going to explode!";
$l_news_c_text100	 = "The aspiring empire of [name] now has 100 million colonists, after an explosion of birth rates, [name] colonies seemed to be a good place for families to settle!";
$l_news_c_text500	 = "The large empire of [name] now has 500 million colonists, [name] said in an interview that colonization of the galaxy has just yet begun";
$l_news_c_text1000	 = "The humongous empire of [name] now has one billion colonists, MNN reporters found out that [name] is in possesion of some weird cloning mechanism allowing him to breed new colonists in huge amounts. With this amount of colonists, the econmic strength of this empire is enormous, MNN hopes that [name] does not spend his money on warfare";

$l_news_indi_short	 = "MNN Rumor: over [planets] declare independance.";
$l_news_indi	 = "MNN has it on good authority that over [planets] planets have decided that they are better ruled by themselves and have become independant.";

$l_news_nova_short	 = "MNN Report: [name] uses Nova Bomb.";
$l_news_nova	 = "MNN has breaking news that [name] has used the feared Nova Bomb [total] time(s) to destroy a planet and all ships on it.";
$l_news_nova_m_short	 = "MNN Report: [name] uses Nova Bomb and misses.";
$l_news_nova_m	 = "MNN has breaking news that [name] has used the feared Nova Bomb [total] time(s) to try and destroy a planet.  The Nova Bomb blew up outside the planets atmosphere and caused massive damage to the planetary infrastructure.";

$l_news_bounty	 = "MNN Report: [name] places a [amount] credit bounty on [name2].";

$l_news_attackerpod_p_short	 = "MNN Report: [name]'s ship is destroyed.";
$l_news_attackerpod_P	 = "[name]'s ship was destroyed while attacking a planet.  Fortunately [name] had an Escape Pod and survived.";

$l_news_attackerdie_p_short	 = "MNN Report: [name] dies!";
$l_news_attackerdie_p	 = "[name]'s ship was destroyed while attacking a planet and they were killed because they failed to purchase an Escape Pod.";

$l_news_destroyed_p_short	 = "MNN Report: [name] attacks and destroys a planet!";
$l_news_destroyed_p	 = "[name] attacked [total] planet(s) owned by [owner] and the population of each planet destroyed the planet to prevent it being captured!";

$l_news_defeated_p_short	 = "MNN Report: [name] attacks and defeats a planet!";
$l_news_defeated_p	 = "[name] attacked [total] planet(s) owned by [owner] and defeated the planetary defense forces!";

$l_news_notdefeated_p_short	 = "MNN Report: [name] attacks a planet and loses!";
$l_news_notdefeated_p	 = "[name] attacked [total] planet(s) owned by [owner] and the planetary defenses held against the relentless attacks!";

$l_news_targetepod_short	 = "MNN Report: [name] attacks a [owner] and wins!";
$l_news_targetepod	 = "[name] attacked [owner]'s ship and destroyed it completely.  Fortunately [owner] had equiped their ship with an Escape Pod and they survived.";

$l_news_targetdies_short	 = "MNN Report: [name] attacks a [owner] and kills them!";
$l_news_targetdies	 = "[name] attacked [owner]'s ship and destroyed it completely.  Sadly [owner] didn't equiped their ship with an Escape Pod and they were vaporized.";



?>
