<?
$l_profile_title = "Profile Registration";
$l_profile_notenabled = "Profiles are not enabled on this server.";
$l_profile_registered = "This player is now registered with the Master Profile Server.";
$l_profile_nomatch = "Could not match a profile on the Master Profile Server with the name and server password entered.";
$l_profile_tryagain = "To enter your player profile name and server password again click ";
$l_profile_name = "Player Name";
$l_profile_password = "Profile Server Password";
$l_profile_bannedserver = "This server is not allowed to submit profile information to the Master Profile Server.";
$l_profile_bannedplayer = "You have been banned from the Master Profile Server and may not register players.";

?>