<?php
$l_die_title             = "Self-Destruct";
$l_die_rusure            = "Activate Self-Destruct?";
$l_die_goodbye           = " Activate Self-Destruct";
$l_die_check             = "Activate Self-Destruct?<br>Your Engines Will Overload And You<br>Will Die In The Resulting Explosion<br><br>Do You Still Wish To Continue?";
$l_die_nonono            = "NO!";
$l_die_what              = " Please De-Activate Self-Destruct";
$l_die_count             = "Engines At Critical<br>Overload In Progress";
$l_die_vapor             = "Your Engines Have Overloaded<br>Your Ship And All Hands Have Been Lost";
$l_die_please1           = "logout";
$l_die_please2           = "Please, [logout_link]";
$l_die_exploit           = "Cheaters NEVER Prosper!!!";
?>
