<?php
$l_att_title             = "Attack Ship";
$l_att_notarg            = "Enemy Has Left This Sector.";
$l_att_noturn            = "You need at least one turn to attack.";
$l_att_noatt             = "Spatial Anomalies Pervent Weapon Systems From Working In This Sector At This Time.";
$l_att_flee              = "Enemy Out Maneuvered You!";
$l_att_ewd               = "Enemy Engaged An Emergency Warp Device And Has Fled The Sector!";
$l_att_att               = "Attacking ";
$l_att_beams             = "Beam Exchange";
$l_att_torps             = "Torpedo Exchange";
$l_att_fighters          = "Fighter Exchange";
$l_att_lost              = "Lost";
$l_att_ylost             = "You Lost";
$l_att_sdown             = "'s Shields Are Down!";
$l_att_ydown             = "Your Shields Are Down!";
$l_att_shits             = "'s Shields Are Hit For";
$l_att_yhits             = "Your Shields Are Hit For";
$l_att_dmg               = "Damage";
$l_att_sarm              = "'s Armor Breached!";
$l_att_yarm              = "Your Armor Has Been Breached!";
$l_att_ashit             = "'s Armor Is Hit For";
$l_att_ayhit             = "Your Armor Is Hit For";

$l_att_efhit             = "'s Fighters Are Destroyed.";
$l_att_yfhit             = "Of Your Fighters Are Destroyed.";
$l_att_ethit             = "'s Torpedoes Are Destroyed.";
$l_att_ythit             = "Of Your Torpedoes Are Destroyed.";
$l_att_of                = "Of";
$l_att_lostt             = "Lost All Torpedoes.";
$l_att_ylostt            = "You Lost All Torpedoes.";

$l_att_lostf             = "Lost All Fighters.";
$l_att_ylostf            = "You Lost All Fighters.";
$l_att_sdest             = "'s Ship Has Been Destroyed.";
$l_att_espod             = "An Escape Pod Was Launched!";
$l_att_ysalv             = "You Salvaged [salv_ore] Units Of Ore, [salv_organics] Units Of Organics, [salv_goods] Units Of Goods, And Salvaged [ship_salvage_rate]% Of The Ship For [ship_salvage] Credits.<BR>Your Rating Changed By [rating_change] Points.";
$l_att_andused           = "And Used";
$l_att_stilship          = "You Did Not Destory Enemy's Ship.";
$l_att_atyou             = "Attacked You";
$l_att_and               = "And";
$l_att_yshiplost         = "Your Ship Has Been Destroyed!";
$l_att_salv              = "Enemy Salvaged [salv_ore] Units of Ore, [salv_organics] Units Of Organics, [salv_goods] Units Of Goods, And Salvaged [ship_salvage_rate]% Of The Ship For [ship_salvage] Credits";
$l_att_loosepod		 = "Make Sure You Buy A New Escape Pod For Your New Ship!";

$l_att_tnobeams		 = " Seems To Be Out Of Beam Energy.";
$l_att_tnobeamsf		 = " Seems To Be Out Of Beam Energy And Cannot Attack Your Fighters.";
$l_att_tnobeamst		 = " Seems To Be Out Of Beam Energy And Cannot Attack Your Torpedoes.";
$l_att_tfnoattack		 = " Isn't Sending Any Fighters To Attack Your Ship.";
$l_att_tnotorps		 = " Seems To Be Out Of Torpedoes.";

$l_att_anobeams		 = "You Have Exhausted Your Ships Beam Energy.";
$l_att_anobeamsf		 = "You Have Exhausted Your Ships Beam Energy And Cannot Attack The Enemy Fighters.";
$l_att_anobeamst		 = "You Have Exhausted Your Ships Beam Energy And Cannot Attack The Enemy Torpedoes.";
$l_att_anofighters		 = "Your Ship Has Exhausted All Availible Fighters.";
$l_att_anotorps		 = "You Have Exhausted Your Availible Torpedoes.";
$l_att_imtitle		 = "Ship Under Attack";
$l_att_imbody		 = "Is Attacking Your Ship.";

$l_att_luckybeams		 = "Enemy BeamsOverload Inflicting";
$l_att_luckyfighters	 = "Enemy Fighters Make A Surprise Lightening Attack And Cause";
$l_att_luckytorps		 = "Enemy Torpedoes Induce A Cascading Damage Effect Causing";
$l_att_luckytimes		 = "Times The Normal Damage!";
?>
