<?php
$l_chf_youretreatback    = "You Order The Helm To Reverse Course,<br> And Return To Your Last Location ";
$l_chf_movefailed        = "Move Failed.";
$l_chf_thefightersdetectyou     = "Sector Fighters On Attack Vector!";
$l_chf_therearetotalfightersindest      = "Sensors Detect [chf_total_sector_fighters] Fighters In The Destination Sector.";
$l_chf_youcanretreat     = "<B>Retreat</B> - Tactical ReTreat Will Cost A Turn But You Will NOT Engange The Defences.";
$l_chf_inputfight        = "<B>Fight</B> - Shields Up Im Going In.";
$l_chf_inputcloak        = "<B>Cloak</B> - Engage Cloaking Device. You May Or May Not Be Seen By The Fighters,<br> However Mines Are Unaffected By Cloaks.";
$l_chf_go                = "Engage";
$l_chf_inputrun        = "<B>Guerrilla Strike</B> - Guerrilla Strike Also Known As Hit & Run.<br>A Quick Attack Followed By A Quick Retreat,<br> Bewarned...You May Still Take Some Damage.";
?>
