<?php
$l_ranks_title           = "Top $max_rank Players";
$l_ranks_none            = "No Results to show.";
$l_ranks_pnum            = "Total number of players";
$l_ranks_dships          = "Players with destroyed ships are not counted.";
$l_ranks_rank            = "Rank";
$l_ranks_lastlog         = "Last login";
$l_ranks_good            = "Good";
$l_ranks_evil            = "Evil";
$l_ranks_regen           = "to recalculate your score.";
$l_ranks_done            = "Your score is recalculated.";
$l_ranks_standing        = "Standing";
$l_ranks_select        = "Select the Ranking Page to view";
$l_ranks_page        = "Page";
$l_ranks_next        = "Next";
$l_ranks_prev        = "Previous";
$l_ranks_online        = "Online";
$l_ranks_rating        = "Eff. Rating";
$l_ranks_show        = "Showing players";
$l_ranks_to        = "to";
$l_ranks_kills        = "Kills";
$l_ranks_deaths        = "Deaths";
$l_ranks_captures        = "Captures";
$l_ranks_lost        = "Lost";
$l_ranks_built        = "Built";
$l_ranks_experience        = "Experience";
?>
