<?
class Basic_Computer {

	var $fighter_damage_shields = 2500; // amount of damage to enemy shield hit points per fighter
	var $fighter_damage_all = 1500; // amount of damage to all enemy items except shields per fighter

	var $fighter_hit_pts = 1750; // the amount of damage a fighter can take before it is destroyed

	var $fighter_price_modifier = 1; // The cost of each fighter is multiplied by this number
}

?>